### ISSUE TITLE
lib/aot/bin/compile-abc/compile-abc is i386 and won't run on macOS Catalina (10.15)

### ISSUE THREAD

**Issue by tuarua** [Gamua/Adobe-Runtime-Support#119]
## Problem Description

macOS Catalina now doesn't support running 32bit apps/binaries.
lib/aot/bin/compile-abc/compile-abc is still only 32bit arch and therefore it is impossible to compile an iOS app for release !

Error is always: Compilation failed while executing : compile-abc

* Which AIR SDK did you use? 
33.2.0.246

* Describe the affected environment: 
AIR iOS on macOS 10.15

* Can you reproduce it yourself, or did you get reports from other users? If so, how many users are affected (percentage)?
Yes

## Steps to Reproduce

* Package an AIR app for iOS with release settings (**without** fast-packaging)

## Known Workarounds

Rollback to macOS 10.14 but this is not possible in all cases.

**Comment by ajwfrost** [comment]
Yes we're aware of this one and are trying to get an update into our forthcoming release to fix this (if we miss that, we'll provide a patch as soon as possible).

**Comment by twistedmedia** [comment]
Thank you!

**Comment by tuarua** [comment]
Fine for me now in 33.2.0.288

**Comment by aldoyh** [comment]
Same issue here with Adobe Animate CC 19.2.1 Build 408

**Comment by ajwfrost** [comment]
@aldoyh Have you updated the SDK to 33.2.0.288 and got Animate to use this one? Worth also checking the compile-abc binary e.g. with "file compile-abc" in a terminal console to check what the format is, in case something went wrong with unpacking the SDK.

**Comment by otololo** [comment]
Where can I find the SDK 33.2.0.288, please? On the [official Harman website I can see only 33.0.2.315](https://airsdk.harman.com/download). Am I missing something?...

**Comment by Oldes** [comment]
@otololo 33.0.2.315 is the latest version. 3.0.2.288 was the previous one.

**Comment by topomonkey** [comment]
The 33.0.2.315 version still throws an error saying that the "adl" cannot be opened because the developer cannot be verified. (on Mac Catalina with animate cc)
Any thoughts?

**Comment by Oldes** [comment]
Just don't use overprotecting Catalina and you will be fine. Everyone who provides apps (even tools like "adl") must send each binary to Apple for "notarization", where Apple analyze the binary and if they think it's ok, they will sign it so users may open it on Catalina.

**Comment by alwinlubbers** [comment]
> The 33.0.2.315 version still throws an error saying that the "adl" cannot be opened because the developer cannot be verified. (on Mac Catalina with animate cc)
> Any thoughts?

When the dialog pops up, click on 'Cancel' and open the 'System Prefrences' app, click on 'Security & Privacy' and go to the 'General' tab. Finally, click on 'Open Anyway'. Publish your app again, now you will see a new 'Open' button in the dialog box. Click on that, and it should be fixed.

**Comment by otololo** [comment]
@Oldes Thank you for the answer.

I'm on macOS Catalina 10.15.1, using Animate 2020. So far, I am not able to generate an IPA at all (I've tried AIR 32 and 33.0.2.315). The 33.0.2.315 version threw the same error about unverified developer, I fixed that using the same steps as @alwinlubbers suggested, thank you. 

Next error was "SDK is missing file arm-air.txt". I’ve found [another forum thread mentioning this issue](https://github.com/Gamua/Adobe-Runtime-Support/issues/112#issuecomment-553851846). As advised there, I downloaded air-fields.arm-air.txt file (they provided a ZIP file link) and placed in the correct folder, but now I get another error: "Invalid input. Struct avmplus::ScopeChain size is incorrect [...] Undefined symbols for architecture armv7". Do I understand it right that it's due to the problem mentioned [here](https://github.com/Gamua/Adobe-Runtime-Support/issues/112#issuecomment-557062721) and there is no fix for now, other than compiling on Windows?

**Comment by Oldes** [comment]
You should be still able to compile on mocOS 10.14 and older. Or maybe use some VM or Docker. Still don't understand why all of you blindly update your OS when is working.

**Comment by alwinlubbers** [comment]
@otololo I'm glad to help. That's excactly the error i've been getting with AIR33 on macOS Catalina. Still haven't tried the AIR33 SDK in Animate on macOS Mojave. I'm still developing with AIR32 as of right now.

@Oldes I know it's kinda dumb to upgrade your OS when everything is working as it should, well apart from the new features, improvements and iOS compatibility. Luckily, i have 2 Macs, but i've  sadly installed Catalina on my main machine. Catalina has been a dumpster fire for me, it's easily the worst version of macOS since Lion.

**Comment by shaymolho** [comment]
Hi,
I also upgraded to MacOS15 and since then can't build the IPA.

I've upgraded the AIR to AIR33, fixed the "ld" security problem the prevented it from running,
but now i got to the following error:

```
Compileation failed while executing : ld64
ld: library not found for -lclang_rt.ios

```
Did anyone encounter this problem?
