### ISSUE TITLE
[AIR 33.1.0.43 beta][tvOS] Application package doesn't work

### ISSUE THREAD

**Issue by itlancer** [Gamua/Adobe-Runtime-Support#234]
## Problem Description
Application package for tvOS target doesn't work with AIR 33.1.0.43 beta.
Package command throw error: `SDK is missing file objects-13.0+.nib`

It has been tested with latest AIR 33.1.0.43 beta with Windows 8.1 64-bit device.
Doesn't tested from macOS yet.

It works fine with AIR 33.0.2.338 and below.

Related issue (not the same): https://github.com/Gamua/Adobe-Runtime-Support/issues/232

## Steps to Reproduce
Try to package any AIR (even "empty") application for tvOS `ipa-ad-hoc` target (with proper `UIDeviceFamily=3` in application manifest).
Execute via command line with Windows device:
`adt -package -target ipa-ad-hoc -storetype pkcs12 -keystore cert.p12 -storepass storepass -keypass keypass -provisioning-profile tvOSProfile.mobileprovision test.ipa test-app.xml test.swf`
with AIR 33.1.0.43 beta adt usage.

**Actual Result:**
You will get error output.
```
SDK is missing file objects-13.0+.nib
```
AIR application will not be packaged.

**Expected Result:**
AIR application for tvOS will be packaged.

## Known Workarounds
none
*Use AIR 33.0.2.338 production version.

**Comment by ajwfrost** [comment]
@itlancer Should be fixed now with 33.1 release, although we don't have our own tvOS support in there yet I'm afraid. So it should still be possible to create tvOS apps, but they will be based on AIR 32 and hence would need to keep the namespace at 32.0.

**Comment by itlancer** [comment]
Still getting the same error
`SDK is missing file objects-13.0+.nib`
with latest AIR 33.1.1.50.
SWF compiled with namespace 32.0. The same namespace in application XML.

**Comment by reckhoff** [comment]
Just wanted to comment that I just installed 33.1.1.50 and am also getting the same missing file objects-13.0+.nib error building my iOS app. (not tvOS).

**Comment by ajwfrost** [comment]
Hi @reckhoff  - did you copy the SDK over the top of a previous one? Apple changed the format of the MainWindow.nib file so that it’s now a folder, with these files within it. I suspect the copy didn’t overwrite the old file with the new folder, hence these missing files..

We really need an “SDK Manager” that can do updates properly (and more efficiently)!

**Comment by reckhoff** [comment]
doh! that teaches me to start a copy and walk away before it finishes. You are correct that they are indeed folders and once I fixed that, I can now build. Thank you for your quick response.

**Comment by kyle620** [comment]
Hi @reckhoff, I am having the same issue as you.  @ajwfrost mentionedI did not copy SDK over the previous one. Where in the SDK can I find the files?

**Comment by kyle620** [comment]
I was able to fix my issue. I downloaded and unzipped the latest sdk.

**Comment by ajwfrost** [comment]
Duplicate of #253 I believe.
Files are in the SDK folder: `\lib\aot\lib` (and `\lib\aot\lib-tvos`)
Previously MainWindow.nib and MainWindow-iPad.nib were files.
Now they are folders, with file contents or MainWindow[-iPad].nib and objects-13.0+.nib.
@itlancer  looks like we missed the tvos one actually in the 33.1.1.50 release, sorry! I will double-check this has been corrected in the new SDK..

**Comment by mattdaboy** [comment]
Thank you, that works fine !

**Comment by itlancer** [comment]
Fixed with AIR 33.1.1.63.
Thank you!
