### ISSUE TITLE
Device soft keyboard doesn't appear when focusing on an input textfield in AIR33

### ISSUE THREAD

**Issue by ajwfrost** [Gamua/Adobe-Runtime-Support#61]
## Problem Description

Using AIR 33 on Android devices (with both ARMv7 and ARMv8 builds)
If you have a TextField on the stage with mode set to 'input', you can touch on this to set the focus and you see the flashing caret, but the device soft keyboard does not appear.
Worked fine when same swf tested on AIR v28.

## Steps to Reproduce

```
        var tf : TextField = new TextField();
        tf.type = TextFieldType.INPUT;
        tf.border = true;
        addChild(tf);
```
And click on the resulting text field..

## Known Workarounds

None - `requestSoftKeyboard()` method doesn't appear to work either.

**Comment by AlexUrrutia** [comment]
It is working for me using Starling/Feathers

_Just want to note that the following helped me in the past (on some devices) to move the application up when showing the Softkeyboard:_
`<application android:hardwareAccelerated="true">`

**Comment by marchbold** [comment]
@AlexUrrutia Was just about to write the same, we have often chased text input and keyboard issues with this change (adding hardwareAccelerated tag) being the fix.

**Comment by ajwfrost** [comment]
Thanks for that hint! We had just been comparing a like-for-like SWF/xml file between the two releases of AIR, so it seems odd still that it doesn't work in v33 but does in v28. I'm assuming that the appearance (or not) of the soft keyboard isn't meant to be dependent upon whether you're using hardware acceleration or not! so we'll still take a look at what's happening here..

**Comment by fhassani** [comment]
I tried setting hardwareAccelerated to true, but soft keayboard still doesn't appear.

**Comment by ajwfrost** [comment]
Fixed in the 33.0.0.212 beta release, I'd be grateful if folk could confirm that the fix works for them!
thanks

**Comment by ajwfrost** [comment]
Closing as we believe this is fixed in anything from 33.0.0.212 onwards..

**Comment by tsanalp** [comment]
This bug still exist. I use LG G4. And no keyboard appears when focus in a textbox. Xperia xz1 device shows the keyboard.
Could you please test?
