### ISSUE TITLE
Permission Error (3800) when calling browseForOpen and browseForSave on MacOS 11

### ISSUE THREAD

**Issue by HarkSolDev** [Gamua/Adobe-Runtime-Support#653]
## Problem Description

I get the following error message "_[Fault] exception, information=PermissionError: 'Error #3800: This call requires Storage permission.' at flash.filesystem::File/browseForOpen()_" when calling file.browseForOpen() and "_[Fault] exception, information=PermissionError: 'Error #3800: This call requires Storage permission.' at flash.filesystem::File/browseForSave()_" when calling browseForSave() on Mac OS 11.1 (Big Sur) when using Air SDK 33.1.1.345, I do not get the error when using 33.1.1.300.

## Steps to Reproduce

// Create new file object.
var file:File = File.documentsDirectory;

// Call browse for open or save.
file.browseForOpen();
file.browseForSave();

I did try calling file.requestPermission() but this makes no difference.

Have I missed something?

**Comment by ffreiberger** [comment]
I have the same problem on all Macs with Air SDK 33.1.1.345

ERROR  on FileReference/download()  form a external url 

[Fault] exception, information=PermissionError: 'Error #3800: This call requires Storage permission.'
at flash.net::FileReference/download()

**Comment by pol2095** [comment]
same problem on Mac OS 11.1

**Comment by ajwfrost** [comment]
This is related to sandboxing, and the restrictions that are in place from Apple on file system access. Looks like we haven't got this right yet (particularly if it's impacting earlier Mac OS versions). Can I check, are you using ADL here, or is this in an application that you've packaged? with or without the captive runtime, and is it signed/notarized?

Plus .. what folders are you actually needing to access here? We're going to have to add some extra permission handling into the runtime, but there would be different requests based on whether you want access just to the user's Documents folder, or various other options for some of the other folders... I'm not sure that we want to trigger a "grant access to all files/folders" request, unless you have an application that really needs that?!

**Comment by ffreiberger** [comment]
Its a Mac captive runtime Application and not signed or notarized.

The the user's Documents folder is sufficient:

We try to download a PDF form a Webserver an save it local.

**Comment by HarkSolDev** [comment]
I am having the issue regardless of whether I am debugging on the ADL, or exported with a captive runtime or after code signed.

I am trying to assess the documents folder. I am able to read and write from to the documents folder directly but unable to open a user dialogue to the documents folder to give the user the option to save and load their data to/from a file of their choice.

With SDK 33.1.1.300 I can open the dialogue with no issues, but not in 33.1.1.345.

**Comment by ajwfrost** [comment]
Okay thanks.. so yes, in the .345 build we added in the new 'permissions manager' capability but the defaults in here look like they've caused a problem when the file open/save browser is being used. For now we can reset the default to assume that the permission is granted, and then will address the other permission requirements for this at a slightly later date.

**Comment by pol2095** [comment]
I tried on Mojave, the same code work.

```
var fileToOpen:File = new File.desktopDirectory;
fileToOpen.browseForOpen("Open");
```

**Comment by pol2095** [comment]
On Mojave, the same code work and "File.perssionStatus" return "granted", on Big Sur "File.perssionStatus" return "unknow"

```
var fileToOpen:File = File.desktopDirectory;
fileToOpen.browseForOpen("Open");
```

I have notarized my app and I have the "Error #3800"

I created an ANE using "NSOpenPanel" and it work correctly

**Comment by HarkSolDev** [comment]
> Okay thanks.. so yes, in the .345 build we added in the new 'permissions manager' capability but the defaults in here look like they've caused a problem when the file open/save browser is being used. For now we can reset the default to assume that the permission is granted, and then will address the other permission requirements for this at a slightly later date.

Thank you the update. Do you know when you plan to release the next version of the SDK?  Then we can make a decision on whether to wait or attempt to work around the issue.

Thanks.

**Comment by rat-moonshine** [comment]
We are having the same problem here. Glad to see this a known problem now )

**Comment by ajwfrost** [comment]
Should be corrected in the SDK version 33.1.1.406, just been uploaded.
Please re-open if there are any issues with it..
thanks

**Comment by spamshaker** [comment]
There is still a problem on Big Sur 11.2.1, I think with the runtime. Cause when I bundle runtime from SDK and make the captive installer like App.app then I can control permission in the Security and Privacy panel (https://support.apple.com/en-us/HT202491). While when I install the runtime AIR runtime - version 33.1.1.385 then it fails. 

Here is the example code. The handler closure is not even called in that version of runtime.
```
package {

  import flash.display.Sprite;
  import flash.events.PermissionEvent;
  import flash.filesystem.File;
  import flash.text.TextField;

  public class Main extends Sprite {
    public function Main() {
      const file: File = File.desktopDirectory;

      file.addEventListener(PermissionEvent.PERMISSION_STATUS, function (event:PermissionEvent) {
        try {
          file.browseForOpen("test");
        } catch (e: Error) {
          var textField: TextField = new TextField();
          textField.width = stage.width;
          textField.height = stage.height;
          textField.text = e.getStackTrace();
          addChild(textField);
        }
      })
      file.requestPermission();
    }
  }
}
```

However by using adl included in the latest SDK with skipping some problematic popups about publisher verification the debug version works and the window is showing
